version: "3"
services:
  web:
    image: 192.168.99.100:55000/ftadverts/ui:ci-${UI_BUILD_NUMBER-1}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3002:3002"
    networks:
      - webnet
    environment:
      - TEAMCITY_PROJECT_NAME	  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
# cadvisor:
#   image: google/cadvisor:latest
#   ports:
#     - "8081:8080"
#   volumes:
#     - "/var/run:/var/run:rw"
#     - "/sys:/sys:ro"
#     - "/var/lib/docker/:/var/lib/docker:ro"
networks:
  webnet: